### ISSUE TITLE
IntelliCache and SMB SR

### ISSUE THREAD

**Issue by Wescoeur** [xapi-project/sm#585]
Just a small question regarding IntelliCache and SMB, I don't understand why the `SR_CACHING` capability is present on this SR: https://github.com/xapi-project/sm/blob/73477116b806c780e435229182c001410596bb13/drivers/SMBSR.py#L33

Because only the NFS type is involved during the cache configuration: https://github.com/xapi-project/sm/blob/73477116b806c780e435229182c001410596bb13/drivers/blktap2.py#L1911

Thank you!

**Comment by MarkSymsCtx** [comment]
That's almost certainly a bug caused by excessive cutting and pasting by the developer when the SMBSR was created. Now whether `blktap2.py` should have been updated to permit the share target to use either NFS or SMB depending on which SR type was in use I can't say. It was probably just missed from consideration of the requirements of the SMB SR.

IMO IntelliCache is of questionable benefit really and the primary drivers for it which existed when it was introduced are probably far less important now than they were.

**Comment by Wescoeur** [comment]
So ok, it makes sense! Thanks for the explanation. :)
